# Generated by Django 4.2.5 on 2023-09-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_categoria_pub_date_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('fecha_publicacion', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
